GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTY1MTk5NzAsImV4cCI6MTU5NjUyMzU3MCwiYXVkIjoiNWYyOGQ4ZjVjOWIxOTY5YmIxMDIxOWFiIiwiaXNzIjoibXl3ZWJzaXRlLmNvbSJ9.Ap1GH6n7sMHXsptC4NGdAeUqnZGospDJUxrihvNHJx8

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user01@gmail.com",
    "password": "1234"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "user01@gmail.com",
    "password": "1234"
}
###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json


{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTY2NzIyMTMsImV4cCI6MTYyODIyOTgxMywiYXVkIjoiNWYyOGQ4ZjVjOWIxOTY5YmIxMDIxOWFiIiwiaXNzIjoibXl3ZWJzaXRlLmNvbSJ9.yfWcSBHwgrh6QwJa2Xnbzh8pAEyVpoRNcjPa0uYJ3QQ"
}
###
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTY2NzU1NDIsImV4cCI6MTYyODIzMzE0MiwiYXVkIjoiNWYyOGQ4ZjVjOWIxOTY5YmIxMDIxOWFiIiwiaXNzIjoibXl3ZWJzaXRlLmNvbSJ9.HhL6lAye55Uw0Uq5Kkx8T8aMIVYR0d8-8t_InYUI1cU"
}